using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Medical.Windows;

[GenerateTypedNameReferences]
public sealed partial class MedicalWindow : DefaultWindow
{
    public MedicalWindow()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetAnchorAndMarginPreset(this, LayoutContainer.LayoutPreset.Center);
        TabContainer.SetTabTitle(OverviewTab, "Overview");
        TabContainer.SetTabTitle(TriageTab, "Triage");
        TabContainer.SetTabTitle(SurgeryTab, "Surgery");
        Tabs.CurrentTab = 0;
    }
}
