- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 # 50 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  supervisors: job-supervisors-centcom
  access:
    - Command
    - Service
    - Brig
    - Maintenance

- type: startingGear
  id: MagistrateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
