using Content.Shared.FixedPoint;
using Content.Shared.Medical.Wounds.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Medical.Controls;

[GenerateTypedNameReferences]
public sealed partial class WoundableEntry : BoxContainer
{
    public WoundableEntry(string woundableName, string severity, Color severityColor)
    {
        RobustXamlLoader.Load(this);
        WoundableName.Name = woundableName;
        Severity.Text = severity;
        Severity.FontColorOverride = severityColor;
    }
}
