- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hrs
  startingGear: LawyerGear
  icon: "JobIconMagistrate"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Command
    - Service
    - Brig
    - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
